---
- name: Create a crackable user account
  hosts: all
  become: yes
  vars_files:
    - files/user_data.yml

  tasks:
    - name: Generate a random password
      set_fact:
        random_password: "{{ accounts[0].password_list | random }}"

    - name: Ensure the user exists
      user:
        name: "{{ accounts[0].username }}"
        password: "{{ random_password | password_hash('sha512') }}"
        groups: []
        state: present
        shell: /bin/bash

    - name: Display user with created credentials
      debug:
        msg: "User {{ accounts[0].username }} created with password {{ random_password }}"
    
    - name: Leak strings to files
      copy:
        content: "{{ item.0 }}"  
        dest: "/home/{{ accounts[0].username }}/{{ item.1 }}"  
        owner: "{{ accounts[0].username }}"
        group: "{{ accounts[0].username }}"
        mode: "0600"
      loop: "{{ accounts[0].strings_to_leak | zip(accounts[0].leaked_filenames) | list }}"
      when: accounts[0].strings_to_leak is defined and accounts[0].leaked_filenames is defined


