---
# tasks file for vulnerabilities/roles/ssh_root_login

- name: Install SSH server packages
  apt:
    name:
      - openssh-server
      - sshpass
    state: present
    update_cache: yes

- name: Enable SSH service
  service:
    name: ssh
    state: started
    enabled: yes

- name: Allow root login via SSH
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
  notify: Restart SSH
      
- name: Generate a random password
  set_fact:
    root_password: "{{ password_list | random }}"
        
- name: Display password
  debug:
    msg: "Root password set to: {{ root_password }}"

- name: Set root password
  command: chpasswd
  args:
    stdin: "root:{{ root_password }}"

- name: Ensure debian user is unlocked
  user:
    name: debian
    password_lock: no
    password: "{{ 'debian' | password_hash('sha512') }}"
    update_password: always
