---
- name: Install and configure Docker
  hosts: testserver
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: Install pip3
      apt:
        name: python3-pip
        state: present
        update_cache: yes


    - name: Install required Python Docker module
      pip:
        name: docker

