---
- name: Configure NFS root share vulnerability
  hosts: testserver
  become: yes
  vars_files:
    - files/nfs_leaked_data.yml

  tasks:
    - name: Install NFS packages
      apt:
        name:
          - nfs-kernel-server
          - nfs-common
          - portmap
        state: present
        update_cache: yes

    - name: Configure NFS exports
      template:
        src: templates/exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: "0777"

    - name: Export NFS shares
      command: exportfs -a

    - name: Leak strings to files
      copy:
        content: "{{ item.0 }}"
        dest: "/root/{{ item.1 }}"
        owner: root
        group: root
        mode: "0666"
      loop: "{{ strings_to_leak | zip(leaked_filenames) | list }}"
      when: strings_to_leak is defined and leaked_filenames is defined

