
- name: Generate random words for the vulnerability
  shell: >
    /opt/venv/bin/python -c
    "from faker import Faker; import random; fake = Faker(); print(' '.join(fake.words(nb={{ num_words }})))"
  register: vuln_flag
  changed_when: false

- name: Ensure directory exists
  file:
    path: "{{ flag_map[item].dir }}"
    state: directory

- name: Create the flag file
  copy:
    dest: "{{ flag_map[item].dir }}/{{ flag_map[item].filename }}"
    content: "{{ vuln_flag.stdout }}"
    mode: '0644'
