---
# tasks file for vulnerabilities/roles/flag

- name: Update apt cache and install required packages
  apt:
    name:
      - python3-pip
      - python3-venv
    state: present
    update_cache: yes

- name: Ensure venv directory exists
  file:
    path: "/opt/venv"
    state: directory
    mode: '0755'

- name: Create virtual environment
  command: python3 -m venv /opt/venv
  args:
    creates: "/opt/venv/bin/activate"

- name: Install Faker in the virtual environment
  pip:
    name: Faker
    virtualenv: "/opt/venv"
    virtualenv_command: python3 -m venv
    

- name: Generate flags for vulnerabilities
  include_tasks: create_flag.yml
  loop: "{{ vulnerabilities_to_flag }}"
  loop_control:
    label: "{{ flag_map[item].dir }}"
  when: flag_map[item] is defined