---
# tasks file for vulnerabilities/roles/flag

- name: Update apt cache and install required packages
  apt:
    name:
      - python3-pip
      - python3-venv
    state: present
    update_cache: yes

- name: Ensure flag directory exists
  file:
    path: "{{ flag_dir }}"
    state: directory
    mode: '0755'

- name: Create virtual environment
  command: python3 -m venv {{ flag_dir }}/venv
  args:
    creates: "{{ flag_dir }}/venv/bin/activate"

- name: Install Faker in the virtual environment
  pip:
    name: Faker
    virtualenv: "{{ flag_dir }}/venv"
    virtualenv_command: python3 -m venv

- name: Choose a random filename from the list
  set_fact:
    flag_filename: "{{ flag_filenames | random }}"

- name: Generate random flag content using Faker (from virtualenv)
  shell: >
    {{ flag_dir }}/venv/bin/python -c "from faker import Faker; import random; fake = Faker(); print(' '.join(fake.words(nb={{ num_words }})))"
  register: flag_content
  changed_when: false

- name: Create flag file with generated content
  copy:
    dest: "{{ flag_dir }}/{{ flag_filename }}"
    content: "{{ flag_content.stdout }}"
    mode: '0644'

