---
- name: Configure SSH root login vulnerability
  hosts: testserver
  become: yes
  vars_files:
    - files/ssh_root_data.yml

  tasks:
    - name: Install SSH server packages
      apt:
        name:
          - openssh-server
          - sshpass
        state: present
        update_cache: yes

    - name: Enable SSH service
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Allow root login via SSH
      template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: "0644"
      notify: Restart SSH
      
    - name: Generate a random password
      set_fact:
        root_password: "{{ password_list | random }}"
        
    - name: Display password
      debug:
        msg: "Root password set to: {{ root_password }}"

    - name: Set root password
      command: chpasswd
      args:
        stdin: "root:{{ root_password }}"

    - name: Leak sensitive files
      copy:
        content: "{{ item.0 }}"
        dest: "/root/{{ item.1 }}"
        owner: root
        group: root
        mode: "0600"
      loop: "{{ strings_to_leak | zip(leaked_filenames) | list }}"
      when: strings_to_leak is defined and leaked_filenames is defined

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted

