---
- name: Install and Configure Backdoored ProFTPD 1.3.3c
  hosts: testserver
  become: yes
  vars_files:
    - files/proftpd_data.yml

  tasks:
    - name: Enable i386 arch
      command: dpkg --add-architecture i386

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dev libs
      apt:
        name:
          - build-essential
          - gcc-multilib
          - libssl-dev
          - libpam0g-dev
          - libssl-dev:i386
          - libpam0g-dev:i386
        state: present



    - name: Copy the tarball
      copy:
        src: "files/proftpd-1.3.3c.tar.xz"
        dest: "/usr/local/src/proftpd-1.3.3c.tar.xz"

    - name: Extract the tarball 
      unarchive:
        src: "/usr/local/src/proftpd-1.3.3c.tar.xz"
        dest: "/usr/local/src"
        remote_src: yes

      
    - name: Configure ProFTPD
      command: ./configure
      args:
        chdir: "/usr/local/src/proftpd-1.3.3c/backdoored_proftpd-1.3.3c"
      register: proftpd_configure
      changed_when: "'creating makefile' in proftpd_configure.stdout|lower or 'created makefile' in proftpd_configure.stdout|lower"


    - name: Make proftpd
      command: "make"
      args:
        chdir: "/usr/local/src/proftpd-1.3.3c/backdoored_proftpd-1.3.3c"
      register: proftpd_make
      changed_when: "'nothing to be done' not in proftpd_make.stdout|lower"

    - name: Make install proftpd
      command: "make install"
      args:
        chdir: "/usr/local/src/proftpd-1.3.3c/backdoored_proftpd-1.3.3c"
      register: proftpd_install
      changed_when: "'nothing to be done' not in proftpd_install.stdout|lower"


    - name: Copy proftpd init.d
      copy:
        src: "files/proftpd.init.d"
        dest: "/etc/init.d/proftpd"
        mode: "0755"
      register: proftpd_init

    - name: Ensure config/log directories exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/proftpd
        - /var/log/proftpd
        - /var/log/proftpd/xferlog
        - /etc/proftpd/conf.d

    - name: Ensure blank config/log files exist
      file:
        path: "{{ item }}"
        state: touch
      loop:
        - /etc/proftpd/modules.conf
        - /var/log/proftpd/proftpd.log

    - name: Remove leftover src files (clean up)
      command: "rm -rf /usr/local/src/*"
      register: directory_cleanup
      changed_when: directory_cleanup.rc == 0


    - name: Create ftp user
      user:
        name: "{{ ftp_user }}"
        home: "{{ ftp_user_home }}"
        create_home: true
        shell: /usr/sbin/nologin

    - name: Set root password
      become: yes
      user:
        name: root
        password: "{{ '12345' | password_hash('sha512') }}"


    - name: Pre-leak files in ftp user home
      copy:
        content: "{{ item.0 }}"
        dest: "{{ ftp_user_home }}/{{ item.1 }}"
        owner: "{{ ftp_user }}"
        group: "{{ ftp_user }}"
        mode: "0600"
      with_together:
        - "{{ strings_to_pre_leak }}"
        - "{{ pre_leaked_filenames }}"


    - name: Leak files in /root 
      copy:
        content: "{{ item.0 }}"
        dest: "/root/{{ item.1 }}"
        owner: root
        group: root
        mode: "0600"
      with_together:
        - "{{ strings_to_leak }}"
        - "{{ leaked_filenames }}"



    - name: Deploy /etc/proftpd/proftpd.conf
      template:
        src: "templates/proftpd.conf.j2"
        dest: "/etc/proftpd/proftpd.conf"
        owner: root
        group: root
        mode: "0644"



    - name: Enable and start proftpd
      service:
        name: proftpd
        enabled: yes
        state: started


