docker_vuln:
  name: grafana
  image: "grafana/grafana:8.0.0"
  ports:
    - "3000:3000"
  env:
    GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_weak_password }}"
  volumes:
    - "/opt/grafana_data:/var/lib/grafana:rw"

